import mongoose from 'mongoose';
import dotenv from 'dotenv';
import User from './models/User.js';
import Product from './models/Product.js';

dotenv.config();

const users = [
  {
    name: 'Admin User',
    email: 'admin@svayam-natural.com',
    password: 'password123',
    role: 'admin',
  },
  {
    name: 'Test User',
    email: 'user@example.com',
    password: 'password123',
  },
];

const products = [
  {
    title: 'Kesh Samraksha',
    slug: 'kesh-samraksha',
    description: 'Nourishing hair pack enriched with 5 potent Ayurvedic herbs to promote hair growth, reduce hair fall, and add salon-worthy shine naturally.',
    price: 399,
    originalPrice: 699,
    inventory: 100,
    images: ['/images/kesh-samraksha/1.jpeg', '/images/kesh-samraksha/2.jpeg', '/images/kesh-samraksha/3.jpeg'],
    category: 'hair-care',
    concern: 'dry-skin',
  },
  {
    title: 'Hibiscus Hair Gel',
    slug: 'hibiscus-hair-gel',
    description: 'Natural hair styling gel infused with hibiscus extract. Strong hold without stiffness, conditions while styling.',
    price: 259,
    originalPrice: 449,
    inventory: 100,
    images: ['/images/hibiscus-night-gel.jpeg'],
    category: 'hair-care',
    concern: 'General',
  },
  {
    title: 'Lavanyam Face Pack',
    slug: 'lavanyam-facepack',
    description: 'Traditional Ayurvedic face pack for radiant, glowing skin. Combines turmeric, sandalwood, and multani mitti to cleanse, brighten, and rejuvenate.',
    price: 499,
    originalPrice: 699,
    inventory: 100,
    images: ['/images/lavanyam/1.jpeg', '/images/lavanyam/2.jpeg', '/images/lavanyam/3.jpeg'],
    category: 'skin-care',
    concern: 'pigmentation',
  },
  {
    title: 'Suryakanti Day Cream',
    slug: 'suryakanti-day-cream',
    description: 'Rise and glow with Suryakanti Day Cream, a luxurious daytime formulation that nourishes, protects, and illuminates your skin with the power of ancient botanicals.',
    price: 999,
    originalPrice: 1299,
    inventory: 100,
    images: ['/images/suryakanti-day-creme.png'],
    category: 'skin-care',
    concern: 'pigmentation',
  },
  {
    title: 'Chandraprabha Night Nectar',
    slug: 'chandraprabha-night-nectar',
    description: 'Intensive night repair cream that is crafted to restore, illuminate and rejuvenate your skin while you sleep.',
    price: 999,
    originalPrice: 1299,
    inventory: 100,
    images: ['/images/chandraprabha-night-necter.png'],
    category: 'skin-care',
    concern: 'anti-ageing',
  },
  {
    title: 'Soumya - The touch of silk Body lotion',
    slug: 'glowup-night-gel',
    description: 'Lightweight body lotion that hydrates without clogging pores. Contains niacinamide and tea tree oil.',
    price: 595,
    originalPrice: 595,
    inventory: 100,
    images: ['/images/glowup-night-gel.jpeg'],
    category: 'body-care',
    concern: 'dry-skin',
  },
  {
    title: 'Rose Lip Balm',
    slug: 'rose-lip-balm',
    description: 'Nourishing lip balm with natural rose extract. Moisturizes and protects lips from dryness with a natural tint.',
    price: 370,
    originalPrice: 499,
    inventory: 100,
    images: ['/images/rose-lip-balm.jpeg'],
    category: 'beauty-products',
    concern: 'dry-skin',
  },
  {
    title: 'Tejasamrit Golden Night Ritual',
    slug: 'tejasamrit',
    description: 'Multi-purpose beauty formulation for face, hair, and body. Enriched with 7 precious ingredients for deep nourishment and radiance.',
    price: 299,
    originalPrice: 999,
    inventory: 100,
    images: ['/images/tejasamrit.png'],
    category: 'beauty-products',
    concern: 'glow-radiance',
  },
  {
    title: 'Triphala Detox Tea',
    slug: 'triphala-detox',
    description: 'Ayurvedic herbal tea blend for natural detoxification. Combines triphala with ginger and tulsi for digestive health.',
    price: 250,
    originalPrice: 399,
    inventory: 100,
    images: ['/images/triphala-detox-powder.png'],
    category: 'natural-food',
    concern: 'General',
  },
  {
    title: 'Gulkand Rose Preserve',
    slug: 'gulkand',
    description: 'Traditional sweet rose petal preserve. Natural coolant with digestive benefits. Made from organic rose petals and sugar.',
    price: 450,
    originalPrice: 599,
    inventory: 100,
    images: ['/images/gulkand/1.png', '/images/gulkand/2.jpeg'],
    category: 'natural-food',
    concern: 'General',
  },
  {
    title: 'Abhyanga Udvartana Oil',
    slug: 'abhyanga-udvartana',
    description: 'Traditional Ayurvedic massage oil for body detoxification. Warming blend of herbs to improve circulation and skin texture.',
    price: 370,
    originalPrice: 849,
    inventory: 100,
    images: ['/images/abhyanga/1.jpeg', '/images/abhyanga/2.jpeg', '/images/abhyanga/3.jpeg'],
    category: 'wellness',
    concern: 'dry-skin',
  },
  {
    title: 'The Complete Radiance Kit',
    slug: 'complete-radiance-kit',
    description: 'A curated kit for radiant skin.',
    price: 1500,
    originalPrice: 2000,
    inventory: 100,
    images: ['/images/Complete-Radiance-Kit.jpeg'],
    category: 'beauty-products',
    concern: 'General',
  },
  {
    title: 'Hair care kit',
    slug: 'hair-care-kit',
    description: 'Everything you need for healthy hair.',
    price: 800,
    originalPrice: 1200,
    inventory: 100,
    images: ['/images/hibiscus-gel-marketing.png'],
    category: 'hair-care',
    concern: 'General',
  },
  {
    title: 'Tejasamrit Golden latte family pack',
    slug: 'tejasamrit-golden-latte-family-pack',
    description: 'Family pack of Tejasamrit Golden latte.',
    price: 900,
    originalPrice: 1200,
    inventory: 100,
    images: ['/images/Eat-To-Glow-Kit.jpeg'],
    category: 'beauty-products',
    concern: 'General',
  },
  {
    title: 'Royal bathing kit',
    slug: 'royal-bathing-kit',
    description: 'Premium bathing essentials.',
    price: 1200,
    originalPrice: 1800,
    inventory: 100,
    images: ['/images/Royal-Bathing-Kit.jpeg'],
    category: 'wellness',
    concern: 'General',
  },
  {
    title: 'Autea',
    slug: 'autea',
    description: 'Natural wellness tea blend.',
    price: 300,
    originalPrice: 450,
    inventory: 100,
    images: ['/images/autea/AUTEA_HERO.png', '/images/autea/1.jpeg', '/images/autea/2.jpeg'],
    category: 'natural-food',
    concern: 'General',
  },
  {
    title: 'Face polishing scrub',
    slug: 'face-polishing-scrub',
    description: 'Face scrub for smooth, glowing skin.',
    price: 400,
    originalPrice: 500,
    inventory: 100,
    images: ['/images/tejasamrit.png'],
    category: 'skin-care',
    concern: 'General',
  },
  {
    title: 'Tarunya Rose Toner',
    slug: 'tarunya-rose-toner',
    description: 'Gentle rose toner for balanced skin.',
    price: 350,
    originalPrice: 450,
    inventory: 100,
    images: ['/images/tarunya-Rose-toner.png'],
    category: 'skin-care',
    concern: 'General',
  },
  {
    title: 'Kumkumadi lip balm',
    slug: 'kumkumadi-lip-balm',
    description: 'Nourishing lip balm with Kumkumadi.',
    price: 250,
    originalPrice: 350,
    inventory: 100,
    images: ['/images/kumkumadi-lip-balm.png'],
    category: 'beauty-products',
    concern: 'General',
  },
  {
    title: 'Abhyanga Natural soap',
    slug: 'abhyanga-natural-soap',
    description: 'Natural soap for body care.',
    price: 150,
    originalPrice: 200,
    inventory: 100,
    images: ['/images/Abhyanga Natural Soap.jpeg'],
    category: 'wellness',
    concern: 'General',
  },
  {
    title: 'Snehchandan natural soap',
    slug: 'snehchandan-natural-soap',
    description: 'Sandalwood-infused natural soap.',
    price: 180,
    originalPrice: 250,
    inventory: 100,
    images: ['/images/Snehchandan Natural Soap.jpeg'],
    category: 'wellness',
    concern: 'General',
  },
  {
    title: 'Soumya – The touch of silk',
    slug: 'soumya-touch-of-silk',
    description: 'Luxurious body care formulation.',
    price: 600,
    originalPrice: 800,
    inventory: 100,
    images: ['/images/tejasamrit.png'],
    category: 'wellness',
    concern: 'General',
  },
  {
    title: 'Mango body butter',
    slug: 'mango-body-butter',
    description: 'Rich mango body butter.',
    price: 500,
    originalPrice: 700,
    inventory: 100,
    images: ['/images/Mango Body Butter.jpeg'],
    category: 'wellness',
    concern: 'General',
  },
  {
    title: 'Kayashuddhi abhyanga body oil',
    slug: 'kayashuddhi-abhyanga-body-oil',
    description: 'Detoxifying body massage oil.',
    price: 450,
    originalPrice: 600,
    inventory: 100,
    images: ['/images/Kayashuddhi Abhyanga Body Oil.jpeg'],
    category: 'wellness',
    concern: 'General',
  },
  {
    title: 'Triphala Natural Soap',
    slug: 'triphala-natural-soap',
    description: 'Triphala-infused natural soap.',
    price: 160,
    originalPrice: 220,
    inventory: 100,
    images: ['/images/tejasamrit.png'],
    category: 'wellness',
    concern: 'General',
  },
  {
    title: 'Keshvardhini hair oil',
    slug: 'keshvardhini-hair-oil',
    description: 'Traditional hair oil for growth.',
    price: 350,
    originalPrice: 500,
    inventory: 100,
    images: ['/images/Keshvardhini Hair Oil.jpeg'],
    category: 'hair-care',
    concern: 'General',
  },
  {
    title: 'Bhruhshakti roll on',
    slug: 'bhruhshakti-roll-on',
    description: 'Natural eyebrow roll-on.',
    price: 200,
    originalPrice: 300,
    inventory: 100,
    images: ['/images/Bhruhshakti Roll On.jpeg'],
    category: 'hair-care',
    concern: 'General',
  },
  {
    title: 'Kesh shuddhi',
    slug: 'kesh-shuddhi',
    description: 'Scalp cleansing formulation.',
    price: 300,
    originalPrice: 450,
    inventory: 100,
    images: ['/images/shudhi/1.jpeg', '/images/shudhi/2.jpeg', '/images/shudhi/3.jpeg'],
    category: 'hair-care',
    concern: 'General',
  },
  {
    title: 'Swarnahairdra Stone grounded 100% pure turmeric',
    slug: 'swarnahairdra-turmeric',
    description: 'Stone-ground pure turmeric powder.',
    price: 250,
    originalPrice: 350,
    inventory: 100,
    images: ['/images/Swarnahairdra Turmeric Powder (400gms).jpeg'],
    category: 'natural-food',
    concern: 'General',
  },
  {
    title: 'Sonamoti Wheat – Nature\'s Gift',
    slug: 'sonamoti-wheat',
    description: 'Premium wheat product.',
    price: 150,
    originalPrice: 200,
    inventory: 100,
    images: ['/images/tejasamrit.png'],
    category: 'natural-food',
    concern: 'General',
  }
];

const seedData = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);

    await User.deleteMany();
    await Product.deleteMany();

    await User.create(users);
    await Product.create(products);

    console.log('Data Seeded Successfully!');
    process.exit();
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};

seedData();
